In [2]:
#read an image 
import cv2


img = cv2.imread('bangaluru.jpg')

cv2.imshow('output Image',img)

cv2.waitKey(0)

cv2.destroyAllWindows()

In [3]:
#write an image 

import cv2 

img = cv2.imread('bangaluru.jpg')

cv2.imshow('orignal Image', img)

cv2.imwrite('output.jpg',img)
cv2.imwrite('output.png',img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
# check the hight and width pixel value 

import cv2


img = cv2.imread('bangaluru.jpg')

# cv2.imshow('output',img)

print(img.shape)
print("hight pixel value :" , img.shape[0])
print("width pixel value :" , img.shape[1])

cv2.waitKey(0)
cv2.destroyAllWindows()

(408, 612, 3)
hight pixel value : 408
width pixel value : 612


## gray scale images  = pixel shades only depends upon black and white 

change color image into gray scale image 

In [8]:
import cv2 

img = cv2.imread('bangaluru.jpg')
cv2.imshow("original",img)

print(img.shape)


cv2.waitKey(0)

gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

cv2.imshow("Gray Scale Image" , gray_img)
print(gray_img.shape)

cv2.waitKey(0)

cv2.destroyAllWindows()

(408, 612, 3)
(408, 612)


In [5]:
import cv2 

img = cv2.imread('bangaluru.jpg',0)
cv2.imshow("gray_scale",img)

cv2.waitKey(0)

cv2.destroyAllWindows()

In [3]:
# Binary 

import cv2 

img = cv2.imread('bangaluru.jpg' , 0)

cv2.imshow("gray", img)
cv2.waitKey(0)

ret , bw = cv2.threshold(img,127,255,cv2.THRESH_BINARY)
cv2.imshow("binary",bw)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# rgb - 0 to 255 , hue - 0 to 180  , saturation - 0 to 255 and value - 0 to 255  

In [3]:
import cv2 

img = cv2.imread("bangaluru.jpg")

# convert into rbg to hsv

img_HSV = cv2.cvtColor(img ,cv2.COLOR_BGR2HSV)

cv2.imshow('HSV Image',img_HSV)

cv2.imshow('hue channel',img_HSV[:,:,0])
cv2.imshow('saturation channel', img_HSV[:,:,1])
cv2.imshow('view channel', img_HSV[:,:,2])

cv2.waitKey(0)
cv2.destroyAllWindows()



In [8]:
import cv2 
import numpy as np 

img = cv2.imread('bangaluru.jpg')
cv2.imshow( 'original' , img)
cv2.waitKey(0)


B,G,R = cv2.split(img)

zeros = np.zeros(img.shape[:2], dtype="uint8")

cv2.imshow('red' , cv2.merge([zeros,zeros,R]))
cv2.waitKey(0)

cv2.imshow('green' , cv2.merge([zeros,G,zeros]))
cv2.waitKey(0)

cv2.imshow('blue' , cv2.merge([B,zeros,zeros]))
cv2.waitKey(0)


cv2.destroyAllWindows()

In [4]:
# image displacement / transplacement 

import cv2 
import numpy as np 
img = cv2.imread('bangaluru.jpg')

# store hight and width of the image 
hight , width = img.shape[:2]
print(hight)
print(width)

quarter_hight ,  quarter_width = hight/4 , width/4 

print(quarter_hight)
print(quarter_width)

# create T translation matrix 

T = np.float32([[1,0,quarter_width],
               [0,1,quarter_hight]])

print(T)

# warpAffine and non worpAffine transform = we used worpAffine 

img_translation = cv2.warpAffine(img , T , (width , hight))
cv2.imshow('original image' ,img)
cv2.imshow('translation' , img_translation)

cv2.waitKey(0)
cv2.destroyAllWindows()




408
612
102.0
153.0
[[  1.   0. 153.]
 [  0.   1. 102.]]


In [7]:
# image rotation 

import cv2 

import numpy as np 

img = cv2.imread("bangaluru.jpg")

hight , width = img.shape[:2]

rotation_matrix = cv2.getRotationMatrix2D((width/2 , hight/2),70, .6)

rotated_image = cv2.warpAffine(img , rotation_matrix , (width , hight))

cv2.imshow('Rotated image' , rotated_image)
cv2.imshow("orignal image" , img)

cv2.waitKey(0)
cv2.destroyAllWindows()





In [9]:
import cv2 

import numpy as np 

img = cv2.imread("bangaluru.jpg")

rotated_img = cv2.transpose(img)

cv2.imshow('Rotated image' , rotated_img)
cv2.imshow("orignal image" , img)

cv2.waitKey(0)
cv2.destroyAllWindows()






In [13]:
# scling resizing and interplotation 

import cv2 
import numpy as np 

img = cv2.imread("bangaluru.jpg")

cv2.imshow("orignal image" , img)

cv2.waitKey(0)

# lets make the size of our image 3/4 of its original image 

img_scaled = cv2.resize(img,None,fx = 0.75 , fy = 0.75)
cv2.imshow('Scaling -Linear Interplotation ' , img_scaled)
cv2.waitKey(0)


img_scaled1 = cv2.resize(img,None,fx = 2 , fy = 2 , interpolation = cv2.INTER_CUBIC)
cv2.imshow('Scaling -Cubic Interplotation ' , img_scaled1)
cv2.waitKey(0)

img_scaled2 = cv2.resize(img,(800,400), interpolation = cv2.INTER_AREA)
cv2.imshow('Scaling -Area Interplotation ' , img_scaled2)
cv2.waitKey(0)






cv2.destroyAllWindows()


In [2]:
# image pyramid - techinc of image resizing 

import cv2 
import numpy as np
img = cv2.imread("bangaluru.jpg")

smaller = cv2.pyrDown(img)
larger= cv2.pyrUp(img)

cv2.imshow('original' , img)
cv2.imshow('larger' , larger)
cv2.imshow('smaller' , smaller)

cv2.waitKey(0)


cv2.destroyAllWindows()



In [6]:
# image cropping 
import cv2 
import numpy as np
img = cv2.imread("bangaluru.jpg")

hight, width = img.shape[:2]

start_row , start_column = int(hight*.5) , int(width*.5)

end_row , end_column = int(hight*.90) , int(width*.90)

cropped = img[start_row:end_row , start_column:end_column]

cv2.imshow('original' , img)
cv2.waitKey(0)

cv2.imshow('cropped' , cropped)
cv2.waitKey(0)

cv2.destroyAllWindows()




In [2]:

import cv2 
import numpy as np 

img = cv2.imread("bangaluru.jpg")

cv2.imshow('original' ,img )
cv2.waitKey(0)

M = np.ones(img.shape , dtype = 'uint8')*150

added = cv2.add(img , M)
cv2.imshow('Added' , added)
cv2.waitKey(0)

sub = cv2.subtract(img , M)
cv2.imshow('sub' , sub)
cv2.waitKey(0)

mul= cv2.multiply(img , M)
cv2.imshow('mul' , mul)
cv2.waitKey(0)

cv2.destroyAllWindows()


In [1]:
# bitwise operations like -- 

import cv2 
import numpy as np 

square = np.zeros((300,300) , np.uint8)

cv2.rectangle(square,(50,50) , (250,250), 255 , -1)
cv2.imshow("square" , square)
cv2.waitKey(0)

ellipse = np.zeros((300,300) , np.uint8)
cv2.ellipse(ellipse,(150,150),(150,150) , 30, 0 , 180 , 255, -1)
cv2.imshow("Ellipse" , ellipse)
cv2.waitKey(0)


And = cv2.bitwise_and(square,ellipse)
cv2.imshow("And",And)
cv2.waitKey(0)

Or = cv2.bitwise_or(square,ellipse)
cv2.imshow("Or",Or)
cv2.waitKey(0)

Not = cv2.bitwise_not(square,ellipse)
cv2.imshow("Not",Not)
cv2.waitKey(0)

Xorr = cv2.bitwise_xor(square,ellipse)
cv2.imshow("XOR",Xorr)
cv2.waitKey(0)


cv2.destroyAllWindows()


In [1]:
# image blurring 
import cv2 
import numpy as np 

img = cv2.imread("bangaluru.jpg")
cv2.imshow('original' ,img )
cv2.waitKey(0)

# creating 3 x 3 kernal
kernal_3X3 = np.ones((3,3), np.float32)/9

# we use the cv2.filter2d to convert kernal with on image 

blurred = cv2.filter2D(img , -1 , kernal_3X3)
cv2.imshow('3x3 kernal blurring ' , blurred)
cv2.waitKey(0)

# creating 7 x 7 kernal
kernal_7X7 = np.ones((7,7), np.float32)/49

# we use the cv2.filter2d to convert kernal with on image 

blurred = cv2.filter2D(img , -1 , kernal_7X7)
cv2.imshow('7x7 kernal blurring ' , blurred)
cv2.waitKey(0)

cv2.destroyAllWindows()


13

In [3]:
# image smoothing 

import cv2 
import numpy as np 

img = cv2.imread("bangaluru.jpg")
cv2.imshow('original' ,img )
cv2.waitKey(0)


blur = cv2.blur(img , (3,3))
cv2.imshow("blur img " , blur )
cv2.waitKey(0)



gaussianblur = cv2.GaussianBlur(img , (7,7) , 0)
cv2.imshow("gblur img " , gaussianblur )
cv2.waitKey(0)


median  = cv2.medianBlur(img , 5)
cv2.imshow("median_blur " , median)
cv2.waitKey(0)

biletral  = cv2.bilateralFilter(img , 9 , 75 , 75)
cv2.imshow("biletral_blur " , biletral)
cv2.waitKey(0)



cv2.destroyAllWindows()






In [2]:
import cv2 
import numpy as np 

img = cv2.imread("bangaluru.jpg" , 0)
height , width = img.shape

# extract slop edges

sobel_x = cv2.Sobel(img , cv2.CV_64F,1,0,ksize = 5)
sobel_y = cv2.Sobel(img , cv2.CV_64F,0,1,ksize = 5)

cv2.imshow('original' , img)
cv2.waitKey(0)

cv2.imshow('sobel x image', sobel_x)
cv2.waitKey(0)

cv2.imshow('sobel y image', sobel_y)
cv2.waitKey(0)


sobel_or = cv2.bitwise_or(sobel_x, sobel_y)
cv2.imshow('sobel or image ' , sobel_or)
cv2.waitKey(0)

laplacian = cv2.Laplacian(img, cv2.CV_64F)
cv2.imshow('Laplacian Image',laplacian)
cv2.waitKey(0)

#Canny Edge detection uses gradiant values as thresholds
canny = cv2.Canny(img, 20, 170)
cv2.imshow('Canny Edge', canny)
cv2.waitKey(0)


cv2.destroyAllWindows()

In [12]:
#Edge Detection
import cv2
import numpy as np

img = cv2.imread("leena.png",0)


height,width = img.shape


#Extract slop edges
sobel_x = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=5)
sobel_y = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=5)


cv2.imshow('Original Image',img)
cv2.waitKey(0)

cv2.imshow('Sobel X Image',sobel_x)
cv2.waitKey(0)

cv2.imshow('Sobel Y Image',sobel_y)
cv2.waitKey(0)

sobel_Or = cv2.bitwise_or(sobel_x,sobel_y)
cv2.imshow('Sobel or Image',sobel_Or)
cv2.waitKey(0)

laplacian = cv2.Laplacian(img, cv2.CV_64F)
cv2.imshow('Laplacian Image',laplacian)
cv2.waitKey(0)

#Canny Edge detection uses gradiant values as thresholds
canny = cv2.Canny(img, 20, 170)
cv2.imshow('Canny Edge', canny)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [14]:
# video capturing 

import cv2 

cap = cv2.VideoCapture(0)

while True :
    
    ret , frame = cap.read()
    cv2.imshow('our live sketch' , frame)
    if cv2.waitKey(1)==13:
        break
        
cap.release()
cv2.destroyAllWindows()

In [1]:
import cv2
import matplotlib.pyplot as plt

cap = cv2.VideoCapture(0)

if cap.isOpened():
    ret, frame = cap.read()
    print(ret)
    print(frame)
else:
    ret = False

img1 = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

plt.imshow(img1)
plt.title('Image Camera-1')
plt.xticks([])
plt.yticks([])
plt.show()

cap.release()

True
[[[252 252 232]
  [252 252 232]
  [253 253 235]
  ...
  [135 130 130]
  [142 130 132]
  [136 125 126]]

 [[251 251 231]
  [252 252 232]
  [252 252 234]
  ...
  [131 124 125]
  [141 132 133]
  [134 125 126]]

 [[251 251 232]
  [251 251 232]
  [252 252 234]
  ...
  [109 104 107]
  [116 111 112]
  [101  96  97]]

 ...

 [[133 100  94]
  [140 107 101]
  [132 101  86]
  ...
  [ 90  89  75]
  [ 88  86  65]
  [ 91  89  69]]

 [[125  96  83]
  [127  98  85]
  [122  92  76]
  ...
  [ 91  93  82]
  [ 94  97  85]
  [ 97  99  88]]

 [[123  94  79]
  [124  96  80]
  [120  89  74]
  ...
  [ 77  78  71]
  [ 66  72  63]
  [ 78  85  75]]]


<Figure size 640x480 with 1 Axes>

In [18]:
import cv2
import numpy as np

def sketch(image):
    #Convert image to grayscale
    img_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    #Cleanup image using gaussian blur
    img_gray_blur = cv2.GaussianBlur(img_gray,(5,5),0)

    #Extract Edges
    canny_edges = cv2.Canny(img_gray_blur, 10, 70)

    #Do an invert binarize the image
    ret, mask = cv2.threshold(canny_edges,70,255,cv2.THRESH_BINARY)
    return mask

cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    cv2.imshow('Our Live Sketch', sketch(frame))
    if cv2.waitKey(1)==13:
        break

cap.release()
cv2.destroyAllWindows()

In [3]:
import cv2
import numpy as np

device  =cv2.VideoCapture(0)
while True:
    ret, frame = device.read()

    hsv = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)

    lower_range = np.array([110,50,50])
    upper_range = np.array([130,255,255])
    mask  =cv2.inRange(hsv, lower_range, upper_range)

    cv2.imshow("show",mask)
    cv2.imshow("show1", frame)

    if cv2.waitKey(1) == 13:
        break

device.release()
cv2.destroyAllWindows()


In [2]:
import cv2
import numpy as np

device  =cv2.VideoCapture(0)
while True:
    ret, frame = device.read()

    hsv = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)

    lower_range_blue = np.array([110,50,50])
    upper_range_blue = np.array([130,255,255])
    mask1  =cv2.inRange(hsv, lower_range_blue, upper_range_blue)

    lower_range_red = np.array([150, 70, 30])
    upper_range_red = np.array([180, 255, 150])
    mask2 = cv2.inRange(hsv, lower_range_red, upper_range_red)

    cv2.imshow("show",frame)

    result1 = cv2.bitwise_and(frame,frame,mask=mask1)
    result2 = cv2.bitwise_and(frame, frame, mask=mask2)

    cv2.imshow("show2", result1)
    cv2.imshow("show3", result2)

    if cv2.waitKey(1) == 13:
        break

device.release()
cv2.destroyAllWindows()